package br.com.zerohora.pusher;

import org.junit.Before;
import org.junit.Test;

import br.com.zerohora.pusher.exception.PusherException;
import br.com.zerohora.repo.ZHRepositoryTest;

/**
 * Copyright 2014 Zero Hora
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * @author isaias_alves <isaiasa@gmail.com>
 */
public class PusherListTest extends PusherList {	
	
	ZHRepositoryTest testInstance = null;
	
	@Before
	public void setUp() throws Exception {
		testInstance = ZHRepositoryTest.getInstance();
		this.setRepo( testInstance.getRepo() ); 
		testInstance.buildArrayAndItem(this.listNews("gremio", 1, 20));
	}
	
	/**
	 * Running repository tests using another array source (generated by mocked listNews callback).
	 */
	@Test
	public void pusherListMustBeValidWithRepositoryValidationInstructions() {
		testInstance.assertAllFieldTypesOfInternalArray();
	}
	
	@Test(expected=PusherException.class)
	public void pusherListMethodMustBeThrowExpectedException() throws PusherException {
		this.listNews("inter", 1, 1000000);
	}
}
